### ISSUE TITLE
Crea una bomba

### ISSUE THREAD

**Issue by JProtyp** [JProtyp/PGPI-P8_KilltheVentana#1]
- La bomba tiene que tener una cuenta regresiva desde 10
- Cuando explote debe mostrar un mensaje: BOOM!!
- Acto seguido debe crear una nueva bomba.

Encargado: @angelsantiago94 

Notificar a: @ostua

**Comment by angelsantiago94** [comment]
Oh capitán, mi capitán.

**Comment by ostua** [comment]
Vale, pero ¿cómo conseguimos que haga BOOM? ¿dónde hay que pinchar?
