### ISSUE TITLE
Crear un bazooka

### ISSUE THREAD

**Issue by JProtyp** [JProtyp/PGPI-P8_KilltheVentana#7]
Desde la resistencia nos han pedido desarrollar armas de larga distancia.

Requerimientos:

- Cuando el programa inicia pide una carga de munición (Usar scanf)
- Tras cargar el arma se dispara. Mostrar un mensaje.
- Tras disparar el arma debe ser desechada. Informar de esto.

Encargado: a Discutir ente @angelsantiago94  @rafesclir @JProtyp

Reportar a: @ostua

**Comment by angelsantiago94** [comment]
Oh mi capitán, @angelsantiago94 se encargará es esto

**Comment by JProtyp** [comment]
Soldado @angelsantiago94, espere órdenes.
Debemos escuchar los reportes del Soldado @rafesclir

**Comment by angelsantiago94** [comment]
A sus ordenes capitán @JProtyp , pero hoy es blackfriday y hay que aprovechar las ofertas
