### ISSUE TITLE
Modificar la bomba para que sea por control remoto

### ISSUE THREAD

**Issue by JProtyp** [JProtyp/PGPI-P8_KilltheVentana#8]
Desde la base de operaciones, nos piden que modifiquemos la bomba para que sea de control remoto.

Esto se refiere a que al introducir un carácter la bomba explote.

Los encargados serán: @angelsantiago94  y @rafesclir 

La solución será la mejor de entre vuestras propuestas.

Reportar a: @ostua

**Comment by angelsantiago94** [comment]
Me encargaré de ello capitán

**Comment by rafesclir** [comment]
Me pongo con esto yo también
